accent = "#ffc600"
cursor = "#ffc600"
foreground = "#ffffff"
background = "#122738"
selection_foreground = "#ffffff"
selection_background = "#0050A4"

color0 = "#000000"
color1 = "#ff628c"
color2 = "#3ad900"
color3 = "#ffc600"
color4 = "#0088ff"
color5 = "#fb94ff"
color6 = "#80fcff"
color7 = "#ffffff"
color8 = "#0050A4"
color9 = "#ff628c"
color10 = "#3ad900"
color11 = "#ffc600"
color12 = "#0088ff"
color13 = "#fb94ff"
color14 = "#80fcff"
color15 = "#ffffff"
